apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: env-pod
  name: env-pod
spec:
  containers:
  - command: ["sh", "-c", "env && sleep 3600"]
    envFrom:
    - configMapRef:
        name: app-config
    image: busybox
    name: env-pod
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 500m
        memory: 128Mi