apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: env-pod-selective
  name: env-pod-selective
spec:
  containers:
  - command: ["sh", "-c", "env && sleep 3600"]
    env:
    - name: COLOR
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_COLOR
    - name: PORT
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_PORT

    image: busybox
    name: env-pod-selective
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 500m
        memory: 128Mi