apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: secret-pod
  name: secret-pod
spec:
  containers:
  - command: ["sh", "-c", "echo User=$DB_USER && echo DB=$DB_NAME && sleep 3600"]
    envFrom:
    - secretRef:
        name: db-secret
    image: busybox
    name: secret-pod
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 500m
        memory: 128Mi